export const ACTION_SET_LOGIN_USER = 'SET_LOGIN_USER';
export const ACTION_SET_IS_LOGIN_VISIBLE = 'SET_IS_LOGIN_VISIBLE';
export const ACTION_SET_IS_REGISTER_VISIBLE = 'SET_IS_REGISTER_VISIBLE';
export const ACTION_SET_CATEGORIES = 'SET_CATEGORIES';
export const ACTION_SET_TOPICS = 'SET_TOPICS';